version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    networks:
      - isolated_network
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  tester:
    build:
      context: ../../
      dockerfile: build/Dockerfile
    container_name: tester-container
    networks:
      - isolated_network
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres-container
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    command: go test -bench=. ./db_experiments/postgresql

volumes:
  postgres-data:

networks:
  isolated_network:
    driver: bridge